// src/pages/SearchPage.tsx
import { useQuery } from '@tanstack/react-query'
import { Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'

import { getGenres, queryKeys, type DiscoverParams } from '@/api/tmdbEndpoints'
import { SearchFilters } from '@/components/search/SearchFilters'
import { MovieCard } from '@/components/movie/MovieCard'
import { EmptyState } from '@/components/ui/EmptyState'
import { MovieGridSkeleton } from '@/components/ui/Skeleton'
import { ErrorState } from '@/components/ui/StatusState'
import {
  sanitizeGenre,
  sanitizeQuery,
  sanitizeRating,
  sanitizeSortBy,
  sanitizeYear,
} from '@/lib/filterValidation'
import { useDebounce } from '@/hooks/useDebounce'
import { useMovieSearch, type SearchMediaType } from '@/hooks/useMovieSearch'

const mediaTypeOptions: Array<{ value: SearchMediaType; label: string }> = [
  { value: 'both', label: 'All' },
  { value: 'movie', label: 'Movies' },
  { value: 'series', label: 'TV Shows' },
]

export function SearchPage() {
  const [searchParams] = useSearchParams()
  const [query, setQuery] = useState(() => sanitizeQuery(searchParams.get('q') ?? ''))
  const [mediaType, setMediaType] = useState<SearchMediaType>('both')
  const [filters, setFilters] = useState<Required<Pick<DiscoverParams, 'genre' | 'year' | 'minRating' | 'sortBy'>>>({
    genre: '',
    year: '',
    minRating: '',
    sortBy: 'popularity.desc',
  })
  const debouncedQuery = useDebounce(sanitizeQuery(query))
  const genres = useQuery({ queryKey: queryKeys.genres, queryFn: getGenres })
  const safeFilters = useMemo(
    () => ({
      genre: sanitizeGenre(filters.genre, genres.data?.genres),
      year: filters.year.length === 4 ? sanitizeYear(filters.year) : '',
      minRating: sanitizeRating(filters.minRating),
      sortBy: sanitizeSortBy(filters.sortBy),
    }),
    [filters, genres.data?.genres],
  )
  const search = useMovieSearch(debouncedQuery, safeFilters, mediaType)

  const movies = useMemo(() => {
    const results = search.data?.results ?? []
    if (!debouncedQuery.trim()) return results
    return results
      .filter((movie) => (safeFilters.minRating ? movie.vote_average >= Number(safeFilters.minRating) : true))
      .filter((movie) => (safeFilters.genre ? movie.genre_ids?.includes(Number(safeFilters.genre)) : true))
      .sort((a, b) => {
        if (safeFilters.sortBy === 'vote_average.desc') return b.vote_average - a.vote_average
        if (safeFilters.sortBy === 'primary_release_date.desc') return b.release_date.localeCompare(a.release_date)
        return b.popularity - a.popularity
      })
  }, [search.data?.results, debouncedQuery, safeFilters])

  const showEmptyPrompt = !debouncedQuery.trim() && !search.isLoading

  return (
    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
      <div className="mb-6 max-w-3xl">
        <p className="text-xs font-medium uppercase tracking-[0.24em] text-[#99AABB]">Search</p>
        <h1 className="mt-2 text-4xl font-bold tracking-tight text-white">Find movies & TV shows</h1>
        <p className="mt-3 text-base text-[#99AABB]">Instant search across TMDB with filters and suggestions.</p>
      </div>

      <div className="space-y-4">
        <div className="grid gap-3 rounded-2xl border border-white/[0.08] bg-[#1C2228] p-3 lg:grid-cols-[1fr_auto] lg:items-center">
          <label className="relative block">
            <span className="sr-only">Search movies and TV shows</span>
            <Search
              className="pointer-events-none absolute left-4 top-1/2 size-5 -translate-y-1/2 text-[#99AABB]"
              aria-hidden="true"
            />
            <input
              className="field h-14 w-full rounded-xl border-white/[0.08] bg-[#202830] !pl-12 !pr-4 text-base"
              placeholder="Search for Breaking Bad, Dune, Parasite..."
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              autoFocus
            />
          </label>
          <div className="flex rounded-xl border border-white/[0.08] bg-[#14181C] p-1" aria-label="Search media type">
            {mediaTypeOptions.map((option) => (
              <button
                key={option.value}
                type="button"
                onClick={() => setMediaType(option.value)}
                className={`flex-1 rounded-lg px-4 py-2 text-sm font-semibold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#00E054] lg:flex-none ${
                  mediaType === option.value
                    ? 'bg-[#00E054] text-[#14181C]'
                    : 'text-[#99AABB] hover:bg-white/5 hover:text-white'
                }`}
              >
                {option.label}
              </button>
            ))}
          </div>
        </div>

        {debouncedQuery.trim() ? (
          <p className="text-sm text-[#99AABB]">
            Showing results for <span className="font-medium text-white">&ldquo;{debouncedQuery}&rdquo;</span>
          </p>
        ) : null}

        <SearchFilters
          genres={genres.data?.genres ?? []}
          genre={filters.genre}
          year={filters.year}
          minRating={filters.minRating}
          sortBy={filters.sortBy}
          onChange={(updates) =>
            setFilters((current) => ({
              ...current,
              genre: updates.genre !== undefined ? sanitizeGenre(updates.genre, genres.data?.genres) : current.genre,
              year: updates.year !== undefined ? sanitizeYear(updates.year) : current.year,
              minRating: updates.minRating !== undefined ? sanitizeRating(updates.minRating) : current.minRating,
              sortBy: updates.sortBy !== undefined ? sanitizeSortBy(updates.sortBy) : current.sortBy,
            }))
          }
        />
      </div>

      <div className="mt-8">
        {search.isLoading ? <MovieGridSkeleton count={12} /> : null}
        {search.isError ? <ErrorState error={search.error} onRetry={() => search.refetch()} /> : null}
        {showEmptyPrompt && !search.isError ? (
          <EmptyState
            title="Start typing to search"
            message="Search movies and TV shows by title. Results update as you type."
          />
        ) : null}
        {!search.isLoading && !search.isError && debouncedQuery.trim() && movies.length === 0 ? (
          <EmptyState
            title="No matches"
            message="Try a broader search, switch between movies and TV shows, or lower the rating filter."
          />
        ) : null}
        {!search.isLoading && !search.isError && movies.length > 0 ? (
          <div className="movie-grid">
            {movies.map((movie) => (
              <MovieCard key={`${movie.media_type ?? 'movie'}-${movie.id}`} movie={movie} />
            ))}
          </div>
        ) : null}
      </div>
    </section>
  )
}

// src/pages/SearchPage.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'
import { Search } from 'lucide-vue-next'
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'

import { getGenres, queryKeys, type DiscoverParams } from '@/api/tmdbEndpoints'
import MovieCard from '@/components/movie/MovieCard.vue'
import SearchFilters from '@/components/search/SearchFilters.vue'
import { useDebounce } from '@/composables/useDebounce'
import { useMovieSearch, type SearchMediaType } from '@/composables/useMovieSearch'
import EmptyState from '@/components/ui/EmptyState.vue'
import MovieGridSkeleton from '@/components/ui/MovieGridSkeleton.vue'
import ErrorState from '@/components/ui/ErrorState.vue'
import { sanitizeGenre, sanitizeQuery, sanitizeRating, sanitizeSortBy, sanitizeYear } from '@/lib/filterValidation'

const mediaTypeOptions: Array<{ value: SearchMediaType; label: string }> = [
  { value: 'both', label: 'All' },
  { value: 'movie', label: 'Movies' },
  { value: 'series', label: 'TV Shows' },
]

const route = useRoute()
const query = ref(sanitizeQuery(typeof route.query.q === 'string' ? route.query.q : ''))
const mediaType = ref<SearchMediaType>('both')
const filters = ref<Required<Pick<DiscoverParams, 'genre' | 'year' | 'minRating' | 'sortBy'>>>({
  genre: '',
  year: '',
  minRating: '',
  sortBy: 'popularity.desc',
})

const sanitizedQuery = computed(() => sanitizeQuery(query.value))
const debouncedQuery = useDebounce(sanitizedQuery)

const genres = useQuery({ queryKey: queryKeys.genres, queryFn: getGenres })

const safeFilters = computed(() => ({
  genre: sanitizeGenre(filters.value.genre, genres.data.value?.genres),
  year: filters.value.year.length === 4 ? sanitizeYear(filters.value.year) : '',
  minRating: sanitizeRating(filters.value.minRating),
  sortBy: sanitizeSortBy(filters.value.sortBy),
}))

const search = useMovieSearch(debouncedQuery, safeFilters, mediaType)

const movies = computed(() => {
  const results = search.data.value?.results ?? []
  if (!debouncedQuery.value.trim()) return results
  return results
    .filter((movie) => (safeFilters.value.minRating ? movie.vote_average >= Number(safeFilters.value.minRating) : true))
    .filter((movie) => (safeFilters.value.genre ? movie.genre_ids?.includes(Number(safeFilters.value.genre)) : true))
    .sort((a, b) => {
      if (safeFilters.value.sortBy === 'vote_average.desc') return b.vote_average - a.vote_average
      if (safeFilters.value.sortBy === 'primary_release_date.desc') return b.release_date.localeCompare(a.release_date)
      return b.popularity - a.popularity
    })
})

const showEmptyPrompt = computed(() => !debouncedQuery.value.trim() && !search.isLoading.value)

function onFilterChange(updates: { genre?: string; year?: string; minRating?: string; sortBy?: string }) {
  filters.value = {
    ...filters.value,
    genre: updates.genre !== undefined ? sanitizeGenre(updates.genre, genres.data.value?.genres) : filters.value.genre,
    year: updates.year !== undefined ? sanitizeYear(updates.year) : filters.value.year,
    minRating: updates.minRating !== undefined ? sanitizeRating(updates.minRating) : filters.value.minRating,
    sortBy: updates.sortBy !== undefined ? sanitizeSortBy(updates.sortBy) : filters.value.sortBy,
  }
}
</script>

<template>
  <section class="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <div class="mb-6 max-w-3xl">
      <p class="text-xs font-medium uppercase tracking-[0.24em] text-[#99AABB]">Search</p>
      <h1 class="mt-2 text-4xl font-bold tracking-tight text-white">Find movies & TV shows</h1>
      <p class="mt-3 text-base text-[#99AABB]">Instant search across TMDB with filters and suggestions.</p>
    </div>

    <div class="space-y-4">
      <div class="grid gap-3 rounded-2xl border border-white/[0.08] bg-[#1C2228] p-3 lg:grid-cols-[1fr_auto] lg:items-center">
        <label class="relative block">
          <span class="sr-only">Search movies and TV shows</span>
          <Search class="pointer-events-none absolute left-4 top-1/2 size-5 -translate-y-1/2 text-[#99AABB]" aria-hidden="true" />
          <input
            v-model="query"
            class="field h-14 w-full rounded-xl border-white/[0.08] bg-[#202830] !pl-12 !pr-4 text-base"
            placeholder="Search for Breaking Bad, Dune, Parasite..."
            autofocus
          />
        </label>
        <div class="flex rounded-xl border border-white/[0.08] bg-[#14181C] p-1" aria-label="Search media type">
          <button
            v-for="option in mediaTypeOptions"
            :key="option.value"
            type="button"
            :class="`flex-1 rounded-lg px-4 py-2 text-sm font-semibold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#00E054] lg:flex-none ${
              mediaType === option.value ? 'bg-[#00E054] text-[#14181C]' : 'text-[#99AABB] hover:bg-white/5 hover:text-white'
            }`"
            @click="mediaType = option.value"
          >
            {{ option.label }}
          </button>
        </div>
      </div>

      <p v-if="debouncedQuery.trim()" class="text-sm text-[#99AABB]">
        Showing results for <span class="font-medium text-white">&ldquo;{{ debouncedQuery }}&rdquo;</span>
      </p>

      <SearchFilters
        :genres="genres.data.value?.genres ?? []"
        :genre="filters.genre"
        :year="filters.year"
        :min-rating="filters.minRating"
        :sort-by="filters.sortBy"
        @change="onFilterChange"
      />
    </div>

    <div class="mt-8">
      <MovieGridSkeleton v-if="search.isLoading.value" :count="12" />
      <ErrorState v-if="search.isError.value" :error="search.error.value" :on-retry="() => search.refetch()" />
      <EmptyState
        v-if="showEmptyPrompt && !search.isError.value"
        title="Start typing to search"
        message="Search movies and TV shows by title. Results update as you type."
      />
      <EmptyState
        v-if="!search.isLoading.value && !search.isError.value && debouncedQuery.trim() && movies.length === 0"
        title="No matches"
        message="Try a broader search, switch between movies and TV shows, or lower the rating filter."
      />
      <div v-if="!search.isLoading.value && !search.isError.value && movies.length > 0" class="movie-grid">
        <MovieCard v-for="movie in movies" :key="`${movie.media_type ?? 'movie'}-${movie.id}`" :movie="movie" />
      </div>
    </div>
  </section>
</template>
